name: Test Action

# Trigger this workflow either manually or when a new change is pushed
on:
  push:
  workflow_dispatch:

jobs:
  test-octave-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Octave action and test command/script
        uses: ./ # run action.yml from the root of this repo
        with:
          command: disp('Action is working as expected')
